baseURL = "https://www.michaeljohnpena.com"
title                         = "ğŸ‘¨ğŸ»â€ğŸ’» MJP âš¡ï¸"
theme                         = "KeepIt"
publishDir                    = "docs"
paginate                      = 12
enableEmoji                   = true
enableRobotsTXT               = true
googleAnalytics               = "UA-186803288-1"

[Author] # Used in authorbox
  name                        = "Michael John PeÃ±a"
  bio                         = "Michael is an experienced technologist based in Sydney, Australia, a Microsoft MVP since 2015 with over 12 years of working experience ranging from Mobile, Cloud, Web and DevOps. He currently owns Datachain Consulting, a company that focuses on democratizing AI and Blockchain technologies. He is also a technical advisor to some technology startups. His roles allow him to explore the cutting edge technologies of Artificial Intelligence, Blockchain, IoT, Edge Computing, and the Cloud."
  customImage                 = "mjtpena.jpg"
  job                         = "Software Engineer"
  gender                      = "male"
  email                       = "michael@datachain.consulting"


[Params]
    since = 2020
    author = "Michael John PeÃ±a"              
    subtitle = "ğŸ‘¨â€ğŸ‘©â€ğŸ‘¦â€ğŸ‘¦ Life. ğŸš€ Technology. ğŸ§  Mind."
    home_mode = "" # post or other

# Navigation bar
[menu]

  [[menu.main]]
  name = "ğŸ˜† About"
  url = "/about" 
  weight = 1
  
  [[menu.main]]
  name = "ğŸ“ Blog"
  url = "/blog" 
  weight = 2

  [[menu.main]]
  name = "âŒš Status"
  url = "/status" 
  weight = 3

  [[menu.main]]
  name = "ğŸ¦¾ Projects"
  url = "/projects" 
  weight = 4 

  [[menu.main]]
  name = "ğŸ‘¨ğŸ»â€ğŸ« Talks"
  url = "/talks" 
  weight = 5 

[Params.gravatar]
    email = "mjtpena@outlook.com"

[Params.Social]
  twitter                     = "mjtpena"
  linkedin                    = "michaeljohnpena"
  github                      = "mjtpena"
  medium                      = "mjtpena"

[Params.Share] # Entry Share block
  facebook                    = true
  twitter                     = true
  reddit                      = true
  linkedin                    = true
  pinterest                   = true

# Web App Manifest settings
# https://www.w3.org/TR/appmanifest/
# https://developers.google.com/web/fundamentals/web-app-manifest/
[Params.Manifest]
  name                        = "Michael John PeÃ±a"
  shortName                   = "mjtpena"
  display                     = "standalone"
  startUrl                    = "/?utm_source=homescreen"
  backgroundColor             = "#8dc153"
  themeColor                  = "#1da1f2"
  description                 = "Personal Site By Michael John PeÃ±a"
  orientation                 = "portrait"
  scope                       = "/"

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType                 = "application/json"
    baseName                  = "manifest"
    isPlainText               = true
    notAlternative            = true

[outputs]
  home                        = ["HTML", "RSS", "MANIFEST"]
